version: '3'
services:
    web:
      image: "quick-blog:latest"
      ports:
        - "9000:9000"
      depends_on:
        - db
      environment:
        - QUICK_BLOG_DB_URL=jdbc:postgresql://db/quickblog
        - APPLICATION_SECRET=asdlkfhqwrtbk2458945yhjksdfgsb8o7klasffg420589uklsgf
    db:
      image: "postgres:10.5"
      volumes:
        - ../bin/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      environment:
        - POSTGRES_PASSWORD=quick-password
